### ISSUE TITLE
Agree on a starter project.

### ISSUE THREAD

**Issue by dwagner4** [onrul/firebase-collab#1]
The classic is to make a real time chat app.  

A more interesting upgrade might be a simple game with real time chat so the players and viewers could talk "smack" at each other.  tic-tac-toe, checkers, maybe a crude 2D shooter?

**Comment by onrul** [comment]
How about checkers with chat and a global leaderboard? # of games won by username.

**Comment by pvestal** [comment]
project agreed upon so closing issue.
